
CREATE TABLE Caelid_Locations (
    id INTEGER PRIMARY KEY,
    location_name TEXT,
    category TEXT,
    subcategory TEXT
);


INSERT INTO Caelid_Locations (location_name, category, subcategory) VALUES 
('Smoldering Church', 'MAIN CAELID', 'Smoldering Church'),
('Rotview Balcony', 'MAIN CAELID', 'Rotview Balcony'),
('Caelem Ruins', 'MAIN CAELID', 'Caelem Ruins'),
('Fort Gael North', 'MAIN CAELID', 'Fort Gael North'),
('Smoldering Wall', 'MAIN CAELID', 'Smoldering Wall'),
('Caelid Highway South', 'MAIN CAELID', 'Caelid Highway South'),
('Cathedral of Dragon Communion', 'MAIN CAELID', 'Cathedral of Dragon Communion'),
('Southern Aeonia Swamp Bank', 'MAIN CAELID', 'Southern Aeonia Swamp Bank'),
('Sellia Backstreets', 'MAIN CAELID', 'Sellia Backstreets'),
('Sellia Under-Stair', 'MAIN CAELID', 'Sellia Under-Stair'),
('Chair-Crypt of Sellia', 'MAIN CAELID', 'Chair-Crypt of Sellia'),
('Church of the Plague', 'MAIN CAELID', 'Church of the Plague'),
('Deep Siofra Well', 'MAIN CAELID', 'Deep Siofra Well'),
('Impassable Greatbridge', 'MAIN CAELID', 'Impassable Greatbridge'),
('Chamber Outside the Plaza', 'MAIN CAELID', 'Chamber Outside the Plaza'),
('Redmane Castle Plaza', 'MAIN CAELID', 'Redmane Castle Plaza'),
('Starscourge Radahn', 'MAIN CAELID', 'Starscourge Radahn'),
('Minor Erdtree Catacombs', 'MAIN CAELID', 'Minor Erdtree Catacombs'),
('Caelid Catacombs', 'MAIN CAELID', 'Caelid Catacombs'),
('War-Dead Catacombs', 'MAIN CAELID', 'War-Dead Catacombs'),
('Abandoned Cave', 'MAIN CAELID', 'Abandoned Cave'),
('Gaol Cave', 'MAIN CAELID', 'Gaol Cave'),
('Gael Tunnel', 'MAIN CAELID', 'Gael Tunnel'),
('Rear Gael Tunnel Entrance', 'MAIN CAELID', 'Rear Gael Tunnel Entrance'),
('Sellia Crystal Tunnel', 'MAIN CAELID', 'Sellia Crystal Tunnel'),
('Aeonia Swamp Shore', 'SWAMP OF AEONIA', 'Aeonia Swamp Shore'),
('Astray from Caelid Highway North', 'SWAMP OF AEONIA', 'Astray from Caelid Highway North'),
('Heart of Aeonia', 'SWAMP OF AEONIA', 'Heart of Aeonia'),
('Inner Aeonia', 'SWAMP OF AEONIA', 'Inner Aeonia'),
('Dragonbarrow West', 'GREYOLLS DRAGONBARROW', 'Dragonbarrow West'),
('Isolated Merchants Shack', 'GREYOLLS DRAGONBARROW', 'Isolated Merchants Shack'),
('Fort Faroth', 'GREYOLLS DRAGONBARROW', 'Fort Faroth'),
('Dragonbarrow Fork', 'GREYOLLS DRAGONBARROW', 'Dragonbarrow Fork'),
('Lennes Rise', 'GREYOLLS DRAGONBARROW', 'Lennes Rise'),
('Farum Greatbridge', 'GREYOLLS DRAGONBARROW', 'Farum Greatbridge'),
('Bestial Sanctum', 'GREYOLLS DRAGONBARROW', 'Bestial Sanctum'),
('Sellia Hideaway', 'GREYOLLS DRAGONBARROW', 'Sellia Hideaway'),
('Dragonbarrow Cave', 'GREYOLLS DRAGONBARROW', 'Dragonbarrow Cave'),
('Divine Tower of Caelid: Center', 'GREYOLLS DRAGONBARROW', 'Divine Tower of Caelid: Center'),
('Divine Tower of Caelid: Basement', 'GREYOLLS DRAGONBARROW', 'Divine Tower of Caelid: Basement'),
('Isolated Divine Tower', 'GREYOLLS DRAGONBARROW', 'Isolated Divine Tower');


CREATE TABLE Caelid_Bosses (
    id INTEGER PRIMARY KEY,
    boss_name TEXT,
    boss_type TEXT,
    location TEXT
);


INSERT INTO Caelid_Bosses (boss_name, boss_type, location) VALUES 
('Decaying Ekzykes', 'Boss', 'Caelid'),
('Flying Dragon Greyll', 'Boss', 'Caelid'),
('Crucible Knight & Misbegotten Warrior', 'Boss', 'Caelid'),
('Elder Dragon Greyol', 'Boss', 'Caelid'),
('Night''s Cavalry', 'Boss', 'Caelid'),
('Nox Swordstress & Nox Monk', 'Boss', 'Caelid'),
('Putrid Avatar', 'Boss', 'Caelid'),
('Putrid Avatar', 'Boss', 'Caelid'),
('Night''s Cavalry', 'Boss', 'Caelid'),
('Godskin Apostle', 'Boss', 'Caelid'),
('Erdtree Burial Watchdog Duo', 'Boss', 'Caelid'),
('Mad Pumpkin Heads (Hammer & Flail)', 'Boss', 'Caelid'),
('Death Rite Bird', 'Boss', 'Caelid'),
('Magma Wyrm', 'Boss', 'Caelid'),
('Putrid Tree Spirit', 'Boss', 'Caelid'),
('Battlemage Hugues', 'Boss', 'Caelid'),
('Fallingstar Beast', 'Boss', 'Caelid'),
('Beastman of Farum Azula', 'Boss', 'Caelid'),
('The Three Crystalians', 'Boss', 'Caelid'),
('Frenzied Duelist', 'Boss', 'Caelid'),
('Cleanrot Knight (Spear) & Cleanrot Knight (Sickle)', 'Boss', 'Caelid'),
('Cemetery Shade', 'Boss', 'Caelid'),
('Black Blade Kindred', 'Great Boss', 'Caelid'),
('Commander O''Neil', 'Great Boss', 'Caelid'),
('Millicent', 'Invasion', 'Caelid'),
('Bell Bearing Hunter (Isolated Merchant Shack)', 'Invasion', 'Caelid'),
('Duelist Knight of the Great Jar x3', 'Invasion', 'Caelid'),
('Starscourge Radahn', 'Legendary Boss', 'Caelid');
