-- Create Locations table
CREATE TABLE Locations (
    id INTEGER PRIMARY KEY,
    location_name TEXT
);

-- Create Bosses table
CREATE TABLE Bosses (
    id INTEGER PRIMARY KEY,
    boss_name TEXT,
    boss_type TEXT,
    location TEXT
);

-- Insert locations into the Locations table
INSERT INTO Locations (location_name) VALUES 
('Church of Elleh'),
('Gatefront'),
('Waypoint Ruins Cellar'),
('Artist''s Shack'),
('Third Church of Marika'),
('Fort Haight West'),
('Agheel Lake South'),
('Agheel Lake North'),
('Church of Dragon Communion'),
('Seaside Ruins'),
('Mistwood Outskirts'),
('Murkwater Coast'),
('Summonwater Village Outskirts'),
('Stormfoot Catacombs'),
('Murkwater Catacombs'),
('Groveside Cave'),
('Coastal Cave'),
('Murkwater Cave'),
('Highroad Cave'),
('Limgrave Tunnels'),
('Cave of Knowledge'),
('Stranded Graveyard'),
('Stormhill Shack'),
('Castleward Tunnel'),
('Margit, the Fell Omen'),
('Warmaster''s Shack'),
('Saintsbridge'),
('Deathtouched Catacombs'),
('Limgrave Tower Bridge'),
('Divine Tower of Limgrave'),
('Church of Pilgrimage'),
('Castle Morne Rampart'),
('Tombsward'),
('South of the Lookout Tower'),
('Ailing Village Outskirts'),
('Beside The Crater-Pocked Glade'),
('Isolated Merchant''s Shack'),
('Fourth Church of Marika'),
('Bridge of Sacrifice'),
('Castle Morne Lift'),
('Behind The Castle'),
('Beside the Rampart Gaol'),
('Morne Moangrave'),
('Impaler''s Catacombs'),
('Tombsward Catacombs'),
('Earthbore Cave'),
('Tombsward Cave'),
('Morne Tunnel'),
('Stormveil Main Gate'),
('Gateside Chamber'),
('Stormveil Cliffside'),
('Rampart Tower'),
('Liftside Chamber'),
('Secluded Cell'),
('Godrick the Grafted');

-- Insert bosses into the Bosses table
INSERT INTO Bosses (boss_name, boss_type, location) VALUES 
('Ulcerated Tree Spirit', 'Boss', 'Limgrave'),
('Soldier of Godrick', 'Boss', 'Limgrave'),
('Grafted Scion', 'Boss', 'Limgrave'),
('Tree Sentinel', 'Boss', 'Limgrave'),
('Demi-Human Chief', 'Boss', 'Limgrave'),
('Erdtree Burial Watchdog', 'Boss', 'Limgrave'),
('Beastman of Farum Azula', 'Boss', 'Limgrave'),
('Crucible Knight', 'Boss', 'Limgrave'),
('Stonedigger Troll', 'Boss', 'Limgrave'),
('Flying Dragon Agheel', 'Boss', 'Limgrave'),
('Bloodhound Knight Darriwil', 'Boss', 'Limgrave'),
('Night''s Cavalry', 'Boss', 'Limgrave'),
('Mad Pumpkin Head', 'Boss', 'Limgrave'),
('Grave Warden Duelist', 'Boss', 'Limgrave'),
('Patches', 'Boss', 'Limgrave'),
('Guardian Golem', 'Boss', 'Limgrave'),
('Black Knife Assassin', 'Boss', 'Limgrave'),
('Night''s Cavalry (Weeping Peninsula)', 'Boss', 'Limgrave'),
('Leonine Misbegotten', 'Boss', 'Limgrave'),
('Tibia Mariner', 'Boss', 'Limgrave'),
('Ulcerated Tree Spirit', 'Boss', 'Limgrave'),
('Demi-Human Queen', 'Boss', 'Limgrave'),
('Cemetery Shade', 'Boss', 'Limgrave'),
('Ancient Hero of Zamor', 'Boss', 'Limgrave'),
('Scaly Misbegotten', 'Boss', 'Limgrave'),
('Deathbird', 'Boss', 'Limgrave'),
('Runebear', 'Boss', 'Limgrave'),
('Miranda the Blighted Bloom', 'Boss', 'Limgrave'),
('Erdtree Burial Watchdog (Impaler''s Catacombs)', 'Boss', 'Limgrave'),
('Deathbird', 'Boss', 'Limgrave'),
('Margit, the Fell Omen', 'Great Boss', 'Limgrave'),
('Erdtree Avatar', 'Great Boss', 'Limgrave'),
('Bloody Finger Nerijus', 'Invasion', 'Limgrave'),
('Anastasia, Tarnished-Eater', 'Invasion', 'Limgrave'),
('Recusant Henricus', 'Invasion', 'Limgrave'),
('Bell Bearing Hunter (Warmaster''s Shack)', 'Invasion', 'Limgrave'),
('Old Knight Istvan', 'Invasion', 'Limgrave'),
('Godrick the Grafted', 'Legendary Boss', 'Limgrave');
