-- Create the Locations table
CREATE TABLE Locations (
    id INTEGER PRIMARY KEY,
    location_name TEXT
);

-- Insert the locations into the table
INSERT INTO Locations (location_name) VALUES 
('Lake-Facing Cliffs'),
('Liurnia Lake Shore'),
('Laskyar Ruins'),
('Scenic Isle'),
('Academy Gate Town'),
('South Raya Lucaria Gate'),
('Main Academy Gate'),
('Liurnia Highway South'),
('Liurnia Highway North'),
('Gate Town Bridge'),
('Artist''s Shack'),
('Eastern Liurnia Lake Shore'),
('Jarburg'),
('Ranni''s Chamber'),
('Eastern Tableland'),
('Church of Vows'),
('Ruined Labyrinth'),
('Mausoleum Compound'),
('Slumbering Wolf''s Shack'),
('Boilprawn Shack'),
('Fallen Ruins of the Lake'),
('Folly on the Lake'),
('Village of the Albinaurics'),
('Converted Tower'),
('Revenger''s Shack'),
('Temple Quarter'),
('Crystalline Woods'),
('Foot of the Four Belfries'),
('The Four Belfries'),
('Sorcerer''s Isle'),
('East Gate Bridge Trestle'),
('Gate Town North'),
('Northern Liurnia Lake Shore'),
('Road to the Manor'),
('Main Caria Manor Gate'),
('Manor Upper Level'),
('Manor Lower Level'),
('Royal Moongazing Grounds'),
('Ranni''s Rise'),
('Behind Caria Manor'),
('The Ravine'),
('Ravine-Veiled Village'),
('Cliffbottom Catacombs'),
('Road''s End Catacombs'),
('Black Knife Catacombs'),
('Stillwater Cave'),
('Lakeside Crystal Cave'),
('Academy Crystal Cave'),
('Raya Lucaria Crystal Tunnel'),
('Study Hall Entrance'),
('Liurnia Tower Bridge'),
('Divine Tower of Liurnia'),
('East Raya Lucaria Gate'),
('Bellum Church'),
('Grand Lift of Dectus'),
('Frenzied Flame Village Outskirts'),
('Church of Inhibition'),
('Ruin-Strewn Precipice'),
('Ruin-Strewn Precipice Overlook'),
('Magma Wyrm Makar'),
('Moonlight Altar'),
('Cathedral of Manus Celes'),
('Altar South'),
('Church of the Cuckoo'),
('Schoolhouse Classroom'),
('Debate Parlor'),
('Raya Lucaria Grand Library');

-- Create the Bosses table
CREATE TABLE Bosses (
    id INTEGER PRIMARY KEY,
    boss_name TEXT,
    boss_type TEXT,
    location TEXT
);

-- Insert the boss data into the table
INSERT INTO Bosses (boss_name, boss_type, location) VALUES 
('Glintstone Dragon Smarag', 'Boss', 'Liurnia'),
('Deathbird (Liurna Lake)', 'Boss', 'Liurnia'),
('Red Wolf of Radagon', 'Boss', 'Liurnia'),
('Night''s Cavalry', 'Boss', 'Liurnia'),
('Magma Wyrm Makar', 'Boss', 'Liurnia'),
('Crystalian (Ringblade)', 'Boss', 'Liurnia'),
('Cleanrot Knight', 'Boss', 'Liurnia'),
('Omenkiller', 'Boss', 'Liurnia'),
('Spear Crystalian & Staff Crystalian', 'Boss', 'Liurnia'),
('Black Knife Assassin', 'Boss', 'Liurnia'),
('Cemetery Shade (Black Knife Catacombs)', 'Boss', 'Liurnia'),
('Death Rite Bird', 'Boss', 'Liurnia'),
('Adan, Thief of Fire', 'Boss', 'Liurnia'),
('Tibia Mariner', 'Boss', 'Liurnia'),
('Night''s Cavalry', 'Boss', 'Liurnia'),
('Spirit Caller Snail', 'Boss', 'Liurnia'),
('Onyx Lord', 'Boss', 'Liurnia'),
('Royal Revenant', 'Boss', 'Liurnia'),
('Bols, Carian Knight', 'Boss', 'Liurnia'),
('Glintstone Dragon Adula (2nd Location)', 'Boss', 'Liurnia'),
('Godskin Noble', 'Boss', 'Liurnia'),
('Erdtree Burial Watchdog', 'Boss', 'Liurnia'),
('Bloodhound Knight', 'Boss', 'Liurnia'),
('Alecto, Black Knife Ringleader', 'Boss', 'Liurnia'),
('Royal Knight Loretta', 'Great Boss', 'Liurnia'),
('Erdtree Avatar', 'Great Boss', 'Liurnia'),
('Erdtree Avatar', 'Great Boss', 'Liurnia'),
('Glintstone Dragon Adula', 'Great Boss', 'Liurnia'),
('Bell Bearing Hunter (Church of Vows)', 'Invasion', 'Liurnia'),
('Moongrum, Carian Knight', 'Invasion', 'Liurnia'),
('Bloody Finger Assassin', 'Invasion', 'Liurnia'),
('Edgar The Revenger', 'Invasion', 'Liurnia'),
('Festering Fingerprint Vyke', 'Invasion', 'Liurnia'),
('Preceptor Miriam', 'Invasion', 'Liurnia'),
('Great Horned Tragoth', 'Invasion', 'Liurnia'),
('Rennala, Queen of the Full Moon', 'Legendary Boss', 'Liurnia');
